apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: hello-listener
spec:
  serviceAccountName: tekton-robot
  triggers:
    - name: hello-trigger 
      interceptors:
        # beta版本不支持，仅在alpha版本支持
        # - cel:
        #     overlays:
        #       - key: "truncated_username"
        #         expression: "body.username.truncate(7)"
        - ref:
            name: "cel"
          params:
            - name: "overlays"
              value:
                - key: "truncated_username"
                  expression: "body.username.truncate(4)"
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "header.match('X-Event', 'curl')"

        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "extensions.truncated_username == \"yang\""

      bindings:
      - ref: hello-binding
      template:
        ref: hello-template
