---
apiVersion: v1 
kind: ServiceAccount 
metadata: 
  name: gitlab-sa
secrets: 
  - name: gitlab-webhook-secrettoken
  - name: gitlab-basic-auth
  - name: docker-credentials
--- 
apiVersion: rbac.authorization.k8s.io/v1 
kind: Role 
metadata: 
  name: tekton-triggers-gitlab-minimal 
rules: 
  - apiGroups: ['triggers.tekton.dev'] 
    resources: 
      ['eventlisteners', 'triggerbindings', 'triggertemplates', 'triggers', 'interceptors'] 
    verbs: ['get', 'list', 'watch'] 
  - apiGroups: [''] 
    resources: ['configmaps'] 
    verbs: ['get', 'list', 'watch'] 
  - apiGroups: ['tekton.dev'] 
    resources: ['pipelineruns', 'pipelineresources', 'taskruns'] 
    verbs: ['create'] 
  - apiGroups: [''] 
    resources: ['serviceaccounts'] 
    verbs: ['impersonate'] 
  - apiGroups: ['policy'] 
    resources: ['podsecuritypolicies'] 
    resourceNames: ['tekton-triggers'] 
    verbs: ['use'] 
--- 
apiVersion: rbac.authorization.k8s.io/v1 
kind: RoleBinding 
metadata: 
  name: tekton-triggers-gitlab-binding 
subjects: 
  - kind: ServiceAccount 
    name: gitlab-sa
roleRef: 
  apiGroup: rbac.authorization.k8s.io 
  kind: Role 
  name: tekton-triggers-gitlab-minimal 
--- 
kind: ClusterRole 
apiVersion: rbac.authorization.k8s.io/v1 
metadata: 
  name: tekton-triggers-gitlab-clusterrole 
rules: 
  - apiGroups: ['triggers.tekton.dev'] 
    resources: ['clustertriggerbindings', 'clusterinterceptors'] 
    verbs: ['get', 'list', 'watch'] 
--- 
apiVersion: rbac.authorization.k8s.io/v1 
kind: ClusterRoleBinding 
metadata: 
  name: tekton-triggers-gitlab-clusterbinding 
subjects: 
  - kind: ServiceAccount 
    name: gitlab-sa
    namespace: default 
roleRef: 
  apiGroup: rbac.authorization.k8s.io 
  kind: ClusterRole 
  name: tekton-triggers-gitlab-clusterrole 