---
apiVersion: v1 
kind: Secret 
metadata: 
  name: gitlab-webhook-secrettoken
type: Opaque 
stringData:
  secretToken: '1234567' 

--- 
apiVersion: v1 
kind: Secret 
metadata: 
  name: gitlab-basic-auth
  annotations: 
    tekton.dev/git-1: http://gitlab.default.svc.cluster.local
type: kubernetes.io/basic-auth
stringData: 
  username: root
  password: B/oAFh1T+NXNqopG4EaGgNWulNWW2kvENP+0T4C66J8=

--- 
apiVersion: v1 
kind: Secret 
metadata: 
  name: docker-credentials
type: kubernetes.io/dockerconfigjson
data: 
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5jbi1ob25na29uZy5hbGl5dW5jcy5jb20iOnsidXNlcm5hbWUiOiJ4eWFuZzA5MTdAcXEuY29tIiwicGFzc3dvcmQiOiJ5YW5neGluMDkxNyIsImF1dGgiOiJlSGxoYm1jd09URTNRSEZ4TG1OdmJUcDVZVzVuZUdsdU1Ea3hOdz09In19fQ==