---
apiVersion: triggers.tekton.dev/v1beta1 
kind: EventListener 
metadata: 
  name: gitlab-listener
spec:
  serviceAccountName: gitlab-sa
  triggers: 
  - name: gitlab-push-events-trigger 
    interceptors: 
    - ref:
        name: gitlab 
      params: 
      - name: secretRef
        value: 
          secretName: gitlab-webhook-secrettoken
          secretKey: secretToken
      - name: eventTypes 
        value: 
          - Push Hook
    bindings: 
    - ref: gitlab-binding 
    template: 
      ref: gitlab-triggertemplate

---
apiVersion: triggers.tekton.dev/v1beta1 
kind: TriggerBinding 
metadata: 
  name: gitlab-binding
spec: 
  params:
    - name: gitrevision 
      value: $(body.checkout_sha) 
    - name: gitrepositoryurl
      value: $(body.project.git_http_url)
    - name: gitreponame
      value: $(body.project.name)

---
apiVersion: triggers.tekton.dev/v1beta1 
kind: TriggerTemplate 
metadata: 
  name: gitlab-triggertemplate 
spec:
  params:
    - name: gitrevision
      description: GIT仓库代码版本
    - name: gitrepositoryurl
      description: GIT仓库地址
    - name: gitreponame
      description: 代码仓库名称
  resourcetemplates:
    - kind: PipelineRun
      apiVersion: tekton.dev/v1beta1
      metadata:
        generateName: gitlab-pipeline-run-
      podTemplate:
        env:
        - name: IMAGE_REGISTRY
          valueFrom:
            configMapKeyRef:
              name: ci-article-registry
              key: ${params.gitreponame}
      spec: 
        serviceAccountName: gitlab-sa
        pipelineRef:
          name: clone-build-push
        params:
          - name: repo-url
            value: $(params.gitrepositoryurl)
          - name: repo-version
            value: $(params.gitrevision)
          - name: image-registry
            value: $IMAGE_REGISTRY:${params.gitrevision}
        workspace:
          - name: shared-data
            volumeClaimTemplate:
              spec:
                volumeMode: Filesystem
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: docker-credentials
            secret:
              secretName: docker-credentials
              items:
                - key: .dockerconfigjson
                  path: config.json
          - name: git-credentials
            secret: 
              secretName: gitlab-basic-auth
      
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-build-push
spec:
  params:
    - name: repo-url
      type: string
    - name: repo-version
      type: string
    - name: image-registry
      type: string
  workspaces:
    - name: shared-data
    - name: docker-credentials
    - name: git-credentials
  tasks:
    - name: print-params
      image: ubuntu
      args: |
        #!/usr/bin/env bash
        echo "$(params.repo-url)"
        echo "$(params.repo-version)"
        echo "$(params.image-registry)"
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
        - name: basic-auth
          workspace: git-credentials
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.repo-version)
    - name: build-push
      runAfter: ["fetch-source"]
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: $(params.image-registry)
      workspaces:
        - name: source
          workspace: shared-data
        - name: dockerconfig
          workspace: docker-credentials