apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: github-build
spec:
  params:
  - name: IMAGE
    description: Name (reference) of the image to build.
    default: registry.cn-hongkong.aliyuncs.com/yangxin/httpserver:v1.0
  - name: DOCKERFILE
    description: Path to the Dockerfile to build.
    default: ./httpserver/Dockerfile
  resources:
    inputs:
    - name: repo
      type: git
  steps:
  - name: github-build
    image: gcr.io/kaniko-project/executor:debug
    workingDir: /workspace/repo
    args:
    - "--dockerfile=./httpserver/Dockerfile"
    - "--context=./httpserver"
    - "--destination=registry.cn-hongkong.aliyuncs.com/yangxin/httpserver:v1.0"
  workspaces:
  - name: dockerconfig
    description: Includes a docker `config.json`
    optional: true
    mountPath: /kaniko/.docker
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: github-build
spec:
  serviceAccountName: xyang0917-sa
  taskRef:
    name: github-build
  resources:
    inputs:
    - name: repo
      resourceRef:
        name: xyang0917-golang
  workspaces:
  - name: dockerconfig
    secret:
      secretName: docker-auth