apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: xyang0917-golang
spec:
  type: git
  params:
    - name: url
      value: https://github.com/xyang0917/golang.git
    - name: revision
      value: master
  secrets:
    - fieldName: authToken
      secretName: github-secrets
      secretKey: token
---
apiVersion: v1
kind: Secret
metadata:
  name: github-secrets
type: Opaque
data:
  token: Z2hwX2FUYmJ6cVV1YmNobFBRQmtiaVk1amJ1RlBRNnROWTE1WDJKMgo= # in base64 encoded form
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-auth
type: Opaque
stringData: 
  config.json: |-
    {
      "auths": {
        "registry.cn-hongkong.aliyuncs.com": {
          "auth": "eHlhbmcwOTE3QHFxLmNvbTp5YW5neGluMDkxNw=="
        }
      }
    }
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: xyang0917-sa
secrets:
- name: docker-auth