apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
  namespace: default
spec:
  params:
  - name: username
    type: string
  steps:
  - name: hello
    image: ubuntu
    command:
    - echo
    args:
    - Hello $(params.username)!
    
    
    